import Head from 'next/head';
import Link from 'next/link';

import { useAppSelector } from '@/hooks/reduxHooks';

export default function Home() {
  const bookmark = useAppSelector((state) => state.bookmark);
  const newTestament = 'new-testament';
  const oldTestament = 'old-testament';

  return (
    <div className="pt-4 container flex flex-col lg:flex-row lg:justify-between lg:py-0 lg:px-4">
      <Head>
        <title>Bible App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="flex flex-col lg:w-2/5 lg:justify-center lg:-mt-24">
        <h1 className="text-6xl font-semibold">The bible</h1>

        <div className="mt-2 mb-6 flex items-center">
          <div className="mt-0.5 mr-2 border-b border-black w-2/4 h-0.5"></div>
          <h2 className="text-lg italic">King James Version</h2>
        </div>

        <p className="w-11/12">
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quidem dolorum accusantium ratione ipsa alias maiores reprehenderit rem
          praesentium aut. Amir dolir sit amet consectetur.
        </p>
        <p className="mt-4 w-11/12">
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quidem dolorum accusantium ratione ipsa alias maiores reprehenderit rem
          praesentium aut. Amir dolir sit amet consectetur.
        </p>
      </section>

      <div className="hidden h-screen border-l border-black lg:block"></div>

      <section className="mt-8 flex flex-col lg:w-2/5 lg:mt-0 lg:justify-center lg:-mt-24">
        <div className="mt-6 flex flex-col items-center gap-y-4 md:flex-row md:gap-x-4">
          <Link
            className="p-4 w-full flex justify-center items-center gap-x-4 bg-white text-center shadow outline-none rounded-full transition ease-in 1s hover:bg-slate-50"
            href={`/${newTestament}`}
          >
            New testament
            {bookmark.testament === newTestament && <i className="mt-1 fa-solid fa-bookmark text-red-500"></i>}
          </Link>
          <Link
            className="p-4 w-full flex justify-center items-center gap-x-4 bg-white text-center shadow outline-none rounded-full transition ease-in 1s hover:bg-slate-50"
            href={`/${oldTestament}`}
          >
            Old testament
            {bookmark.testament === oldTestament && <i className="mt-1 fa-solid fa-bookmark text-red-500"></i>}
          </Link>
        </div>

        <p className="hidden mt-8 lg:block">
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quos vitae earum inventore, explicabo excepturi sit cumque recusandae
          error possimus accusamus ex, ipsa, incidunt commodi illum doloremque adipisci eum deleniti. Natus.
        </p>
      </section>
    </div>
  );
}
