import Head from 'next/head';
import { useRouter } from 'next/router';

import useBook from '@/hooks/useBook';
import { FontSizeContextProvider } from '@/context/FontSizeContext';

import NavBar from '@/components/page-components/chapter/NavBar';
import Chapters from '@/components/page-components/chapter/Chapters';
import BookmarkBtn from '@/components/page-components/chapter/BookmarkBtn';

export default function Chapter() {
  const router = useRouter();
  const { testament, book, chapter } = router.query as { testament: string; book: string; chapter: string };
  const bookToParse = useBook(book, testament);

  if (chapter === undefined || bookToParse === undefined) return <>Loading...</>;

  return (
    <>
      <Head>
        <title>Bible App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BookmarkBtn testament={testament} book={book} chapter={chapter} />

      <FontSizeContextProvider>
        <Chapters bookToParse={bookToParse} chapter={chapter} />
        <NavBar testament={testament} book={book} chapter={chapter} bookToParse={bookToParse} router={router} />
      </FontSizeContextProvider>
    </>
  );
}
