import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { motion } from 'framer-motion';

import useBook from '@/hooks/useBook';
import { useAppSelector } from '@/hooks/reduxHooks';

import Loading from '@/components/Loading';

export default function Chapters() {
  const bookmark = useAppSelector((state) => state.bookmark);
  const router = useRouter();
  const { book, testament } = router.query;
  const bookToParse = useBook(book as string, testament as string);

  if (bookToParse === undefined) return <Loading />;

  return (
    <>
      <Head>
        <title>Bible App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="w-full h-12 flex items-center justify-center text-2xl font-semibold italic">{bookToParse.book}</h1>
      <motion.section
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.5 }}
        className="mt-4 container flex flex-wrap gap-4 justify-center"
      >
        {bookToParse.chapters?.map(({ chapter, verses }) => (
          <Link key={chapter} href={`/${testament}/${book}/${chapter}`} className="p-2 w-1/3 h-full bg-white shadow rounded-lg">
            <div className='flex flex-col items-center'>
              <p className="font-semibold underline">Chapter {chapter}</p>
              <p>{`${verses.length} verses`}</p>
            </div>
            {/* <svg className="mt-0.5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
              <path fill="none" d="M0 0h24v24H0z" />
              <path d="M16 12l-6 6V6z" />
            </svg> */}

            {bookmark.book === book && bookmark.chapter === chapter && <i className="ml-2 fa-solid fa-bookmark text-red-500"></i>}
          </Link>
        ))}
      </motion.section>
    </>
  );
}
