import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { motion } from 'framer-motion';

import useBook from '@/hooks/useBook';
import { useAppSelector } from '@/hooks/reduxHooks';

import Loading from '@/components/Loading';

export default function Chapters() {
  const bookmark = useAppSelector((state) => state.bookmark);
  const router = useRouter();
  const { book, testament } = router.query;
  const bookToParse = useBook(book as string, testament as string);

  if (bookToParse === undefined) return <Loading />;

  return (
    <>
      <Head>
        <title>Bible App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="w-full h-12 flex items-center justify-center text-2xl font-semibold italic">{bookToParse.book}</h1>
      <motion.section
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.3 }}
        className="mt-4 container flex flex-wrap gap-4 justify-center"
      >
        {bookToParse.chapters?.map(({ chapter, verses }) => (
          <Link key={chapter} href={`/${testament}/${book}/${chapter}`} className="relative p-2 w-1/4 h-full bg-white shadow rounded-lg lg:max-w-max transition ease-in 1s hover:bg-slate-100">
            <div className='flex flex-col gap-y-1 items-center'>
              <p className="w-2/5 font-semibold border-b text-center border-slate-400">{chapter}</p>
              <p className='text-sm'>{`${verses.length} verses`}</p>
            </div>
            {bookmark.book === book && bookmark.chapter === chapter && <i className="fa-solid fa-bookmark absolute right-1.5 top-0 text-red-500"></i>}
          </Link>
        ))}
      </motion.section>
    </>
  );
}
